### ISSUE TITLE
Design Meeting Agenda for Sept. 30, 2021

### ISSUE THREAD

**Issue by rcurtis2** [hackforla/design-systems#128]
### Overview
Weekly meeting to review, make decisions, and ask questions about work that is completed and upcoming for the Design Systems UI/UX team

### Action Items

- [x] Review combined design system and gather feedback
- [x] Review and add to decision justifications for each part of design system
- [x] Review each part of the design system for inconsistencies

**Comment by daniellex0** [comment]
**Minutes - September 30, 2021**

**Overall Design System Layout**

- Danielle said projects will likely need to put the entire design system (all components, etc) in one tab as opposed to several different tabs for each component, in order to overcrowd and mess up that project's Figma file. 
   - (Major companies can have design system Figma files with separate tabs for each component because they have paid accounts with the ability to pull those components to separate Figma files.
- Secondary options: discussion ensued about whether to put the secondary versions of sections with two options (like grids, colors, etc.) on a separate tab, or side-by-side
   - Anh: putting them in a separate tab would make them seem like the 'stepchild' - unimportant, people won’t look at it
      - Anastasia agreed
   - Danielle: would it be a problem that we're not emphasizing the version we preferred? (since we usually had a 'winner' primary version, and a secondary version in case projects want that instead.
      - Team didn't think this would be an issue
   - In the end we decided to put both options next to each other in the design system Figma, with explanations of why there are two options

**Design System Decision Justifications**

- Referencing our previous meeting minutes, the team went through the Colors and Typography sections (two versions each) and typed up (in Figma) the decision justifications for all of the choices we made in how we designed them.
   - This will be added to the Wiki documentation so that future members can understand the choices we made with the Figma design system
- We didn't have time to get to the rest, but they are better covered by the meeting minutes and less complicated to type up. This will be done later.

**‘Definition of Done’ Audit**
- Ryan explained that we will need to research and find examples of checklists online that outline what needs to be included in a design system - so that we can get a better idea of what the 'definition of done' for design systems at Hack for LA's projects should be
- Hana asked if we would prefer to research first and then write what we each think our design system 'definition of done' is, or write ours down first and then research later
   - Decision: research common design system checklists first, then make out own checklist when done (this way our checklist is more informed)
   - We will eventually write our own 'definition of done' for Hack for LA project design systems in this spreadsheet:
https://docs.google.com/spreadsheets/d/1BlfLbyPUyIJ-xE4wftO_-UXNjtOIsn4NMJ7WTiIXNyI/edit#gid=730195697 
- The purpose of this is so that we know the base level where a project started ("in the beginning of the design systems project, x out of 25 projects had design systems, this is how complete they were, etc.") so that we can compare future developments and measure impact of the project ("in the end, x out of 25 projects now have design systems and they are this level of complete"). This will help HfLA measure success, and also help with our portfolio/interviews etc (by including measurable success metrics)
- Each person will have an issue assigned to them with this same assignment, to complete by next Tuesday's meeting 
   - (there are separate issues because there shouldn’t be multiple people assigned to one issue)

**Comment by rcurtis2** [comment]
This issue is complete and can be closed.
