### ISSUE TITLE
Design Meeting Agenda for November 23rd, 2021

### ISSUE THREAD

**Issue by rcurtis2** [hackforla/design-systems#227]
### Overview
Weekly meeting to review, make decisions, and ask questions about work that is completed and upcoming for the Design Systems UI/UX team

### Action Items

- [ ] Discuss meeting time
- [ ] Discuss insights on wiki and figma audits 
- [ ] Go over plan for next week's assignment

### Resources/Instructions
[Zoom Link
](https://www.google.com/url?q=https://stanford.zoom.us/j/92192757260?pwd%3DK1FwRkw4L1hQaGk4QXpSczZiR0RIUT09&sa=D&source=calendar&usd=2&usg=AOvVaw30C3I6TQ_oygRQ035-hCAP)
[Figma Audit file](https://docs.google.com/spreadsheets/d/1FLMtxKobteA-dJ7ZK59-Ddn5abVOxJQFCZCJRNNvKM4/edit#gid=1650105889)
[Wiki Audit](https://docs.google.com/spreadsheets/d/1Fc4TvyZA3uukK7461Q_VSwtKEGS-i7UIaWvBt1W7keU/edit#gid=0)
[Figjam for insights brainstorming](https://www.figma.com/file/mmvbxZ6lctjQneEeqTjC8O/Design-Check-list?node-id=0%3A1)

**Comment by JeannyRen** [comment]
Questions and comments that pop up when reading through the wiki and figma audit files:
-	Are there any trends to see with regards to team size in terms of wiki completeness?
-	Do you notice a correlation between project length and wiki or figma completeness?
-	Is there a difference to observe with regards to the aims/goals/nature of the individual projects? 
-      You can measure completeness from the Figma file in % and see if that overlaps with the % of completeness of the Wiki audit file.
- Example of reporting quantitative results: Of all 19 projects that have a Figma file (cleaning stage 1), only 5 had a table of content: 26%. Excluding our own Figma (cleaning stage 2), only 4 out of 18 is 22%. Or put otherwise only 2 out of 10 projects provided a table of content on their Figma files.
- For one project 23 out of 40 people can edit the Figma file: 58% or almost 6 out of 10 team members/at least 5 out of 10 team members can edit the Figma file. 

A more general comments:
- In the future, if there are more projects or teams you need to research you can code the yes/no measurement differently. By e.g. assigning 0 for no and 1 for yes. Then you can calculate the numbers more quickly once you need to analyze them.
