### ISSUE TITLE
Agenda for week of 13th December 2021 

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#243]
Overview
This issue tracks the agenda for the design systems meetings and weekly roll call for projects.

Today's session is the last one of 2021. Work will commence for the last couple of weeks however the team have added their availability for meetings to the [Roll Call Spreadsheet](https://docs.google.com/spreadsheets/d/1JtJGxSpVQR3t3wN8P5iHtLZ-QEk-NtewGurNTikw1t0/edit#gid=0)

As discussed in a previous [Team meeting ticket](https://github.com/hackforla/design-systems/issues/238): The below is what is needed for before the end of the year.

- [x]  Recruitment Survey out (Deadline 16th Nov)
- [x]  Google Drive organised
- [x]  Interview scripts all completed
- [x]  Wiki and Figma Insights document combined (Deadline 30th Nov)
- [ ]  Confirm at least 13 interviews.
- [ ]  Research sections to be updated in the Wiki
- [ ]  UX/UI sections to be updated in the Wiki
- [ ]  Foundation draft complete
- [ ]  Wiki template complete

### Action Items

- [x] PM end of year summary
- [x] Research update
- [x] Design Update

Areas to discuss:

- [ ] Figma report
- [ ] Wiki report
- [x] Onboarding  - #246 #245 #244 
- [x] Wiki #236 #136 
- [x] New open roles #249 #250 #248 #247 

### Resources/Instructions

[Wiki and Figma Draft Audit. ](https://drive.google.com/drive/u/0/folders/1teY-wD3APs-R_KM-AguGIiie_gxX8LNf)

**Comment by Hanastevenson** [comment]
Here are the meeting notes. I have added new tickets and updated the board. 

**General team:**
A number of you are interviewing and will be moving on from the project in January. This is why we need to collate our insights and help new joiners by sharing our knowledge and setting up a better onboarding process to  the team.

If you are not assigned a ticket please take #244  #245  #246 . This is an opportunity for you to dive into the world of Onboarding. Add actions and duplicate the ticket.

**Research:**
Work due for the first meeting in January.
Wiki (feel free to send it to me for feedback)
A member of the team to write a open role post Ticket #247
Affinity sort insights from interviews
Book more interviews for January
If you are not assigned a ticket please take #244 #245 #246 . This is an opportunity for you to dive into the world of Onboarding. Add actions and duplicate the ticket.

PM to speak to Bonnie about recruiting people to interview.

**UX/UI:**
Combine the two drafts in the Figma. Ryan to complete ticket.
First draft of the Wiki
A member of the team to write a open role post Ticket #249
If you are not assigned a ticket please take #244 #245 #246 . This is an opportunity for you to dive into the world of Onboarding. Add actions and duplicate the ticket.

**Comment by JeannyRen** [comment]
Notes UXR meeting on December 14
- Jeanette and Nasim did the first user interview this weekend and tested out the whole procedure. Pre, during, and post-interview handlings went according to plan. Nevertheless, see blockers for the transcription caveat for the Zoom Pro Account.
- Forgot to discuss this, but the interview script is a bit long. So in case the interviewee already answered a question that is posed later down in the script, please think about managing time and the most important information needed.
- Two more interviews are planned for this week.
- Jeanette will look into the possibilities for us to access Lookback, since they have opened up a new possibility for students to work with the software for free. Prerequisite is that you need to be a student for a course where the instructor asked permission for this use. 

Blockers: 
- Zoom transcription: Despite being the host and having a full say over the recordings and the closed captions function, the current Zoom Pro account does not seem to save the transcriptions for people who have been added to the Zoom Pro account. @nasimbiglari will take this issue up by contacting the help desk through the Zoom Pro account.
- In case the solution cannot be found, we will check if a monthly Otter subscription would work to save the day regarding the transcriptions.

**Comment by JeannyRen** [comment]
As of December 16, two user interviews have been conducted. 

Blocker mentioned during the UXR meeting this week is resolved.
