### ISSUE TITLE
1b. Design System Video

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#261]
Copy the template below. Click the green "New Issue" button, and paste the template in.

```
At Figma's conference on design systems in 2020, one talk that stood out was "Reimagining Atlassian Design System" by Jennie Yip.

### Action Items

- [ ] Watch [Reimagining Atlassian Design System- Jennie Yip](https://www.youtube.com/watch?v=_pfyLVXTVSQ)
- [ ] Add your comments and key learnings to [Discussion thread](https://github.com/hackforla/design-systems/discussions/170)
```

**Comment by JeannyRen** [comment]
Hi! @nansah, are you working on this ticket? This specific ticket is the template. Please create your own ticket by copy pasting the template as you can find here https://github.com/hackforla/design-systems/wiki/Your-first-Issues-(ticket), so that this ticket stays in the Onboarding Column of the Github board.

**Comment by kelenelee** [comment]
merged into https://github.com/hackforla/design-systems/issues/260
