### ISSUE TITLE
Overview Agenda for week of July 26th 2021

### ISSUE THREAD

**Issue by Hanastevenson** [hackforla/design-systems#27]
### Overview
There are a couple of new members joining the team therefore we need to introduce them to the project. We will also be discussing team processes and assigning tickets.

### Action Items

- [x] Introductions
- [x] Double diamond
- [x] Team processes
- [x] Team structure
- [x] Assign tickets from backlog
- [x] Dev's to chat about their meeting

**Comment by lorenzejay** [comment]
I have access to the project.

**Comment by BobbyBishopUX** [comment]
Access confirmed.

**Comment by qiqicodes** [comment]
Hope this [2020 Sparkbox DS Survey](https://designsystemssurvey.seesparkbox.com/2021/) can help with our survey script.

Some sample questions that might help with our process:
1. Do we want pure documentation like [Docusaurus](https://docusaurus.io/) for our code or an interactive GUI tool like [Storybook](https://storybook.js.org/)?
2. Do developers prefer creating project from building components from scratch (sandboxing) or creating from boilerplate
3. In order to figure out the success metrics, how much time our current ui/pm/dev currently use to deploy the prototype, from design to minimum viable product?

**Comment by nasimbiglari** [comment]
I have access.

**Comment by hanapotski** [comment]
🙌

**Comment by kelenelee** [comment]
[minutes for this meeting](https://docs.google.com/document/d/1zwdsFduVMXm-sYs03rbBAwd2xzWeuMkf2fxgdZWFGpI/edit)

Double Diamond Process

    Design frameworks build trust and confidence amongst stakeholders
        Current stakeholder: Bonnie (Director of HfLA)

DD - developed by Design Council UK


Diamond 1 - Designing the right thing

    Discover
        Research -> leads to significant insights

Approach us with potential problem or issue they want us to execute
Figure out the brief together with the client
We challenge every part, before we dive into research and dive it into top picks
Really need to define the scope, that you have to think about the different types of exercise

The real benefit of research is to uncover problems or behaviors that leave to significant insights

    Define
    Synthesis
Analyze Research
And cluster the insights into different themes
Then identify problem areas and targeted user groups
Find opportunity areas

How Might We Statement (broad, but also defined)
Bank: Our user is Sam, and they need X, Y, Z
Through Research: we created problem and research
And found a different problem
Example: “How might we help Sam save for retirement considering he is a carefree millennial?”
Deduced the actual question to solve 

(Hfla - design systems -> we are currently in discovery phase)


Diamond 2 - Designing the thing right
Develop
Create ideas and see what is the potential solution for our problem / goal.
Build (MVP)
Evaluate (Is what we did the right solution?)
Iterate
repeat
Deliver





---

Combine Designers and Researchers together
PMs
Developers

How are we going to gather the insights
And the recording for it
And building it for their portfolios (case studies)

Recruit five people from each of those roles

Design Research Team
    Interview team about interview goals
    Create chat in Slack channel or create Slack group
    UX/UI team also welcome to user journeys
    
    Identify: roles, also help out with the design system and uncovering unknown behaviors and insights
    Kiki - great resource for accessibility into interviewing questions
    
UX/UI Team

--

Ticket #2
    Look at how people have used the Figma document and guide people through the Figma document
    For research, how do people link from one page to another
    

Have a large read of the Google document
Have a look at the prioritized backlog

Researchers - need support from team members
Chatting that point with developers
Access to the roster for the team
