### ISSUE TITLE
Listening to the Stakeholder interview

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/design-systems#325]
### Overview
In order to fully understand the reasons behind changing parts of the roadmap and research objectives, it's vital to listen to the stakeholder interview. As you are listening to this interview please keep in mind the objectives of it:

- Identify business Goals and expectations.
- Understand the background of the project and its constraints.
- Identify the pain points.
- Discover the best approach to implement the design system
- Explore the possible effect of the design system on the team onboarding.
- Identify the types of projects in which the design system could be beneficial

### Action Items

- [x] Listen to the stakeholder interview
- [x] Makes note on things that stood out for you ( This can be a theme, pattern, interesting observation)
- [x] share your notes in the comment section below

### Resources/Instructions
[Stakeholder interview](https://drive.google.com/drive/u/0/folders/150KlP6XgUIhdNvvo9NseI0cP8mtn1KrB)

**Comment by hdchangie** [comment]
Dongchen's note: 
Pain points: 
- no coherent design system across projects at Hack for LA so people always have to start from scratch; 
- new joiners (esp. junior people) feel confused if there's no design system in the organization; 
- volunteers come and go; seasonal fluctuations that may affect the sizes of projects; 
- lack organizations guideline so personal charisma (esp. when an excellent volunteer comes) is playing an important role in retaining volunteers (and also can bring volunteers away from HfLA); 

Opportunities (if we have a coherent design system): 

- brand-building and -awareness; 
- have a coherent and basic/useful design system for people to grab and modify so they can begin to build immediately;
- envision a living and dynamic design system for the organization that can be constantly updated by teams/users;
- helpful with retention by providing a clearer roadmap for newcomers; 
- alleviate the burden from the stakeholders so she can work on something more important (expand the whole organization, etc.)

**Comment by kmedhi** [comment]
Notes on the stakeholder interview:
1) The project is a substantial addition to HfLA since it will provide the basis for a design system (guide) for several other cross-functional teams to refer to when needed.
2) The existence of a design system will ease the workload on part of the stakeholder as she, at this point in time, has to refer to individuals and teams towards specific templates and guides for their projects. It will also represent a universal guide for teams that need to build everything from scratch at times of need. 
3) The stakeholder believes that the speed and efficiency of all projects could be increased by making the design system available for all. It will also increase the tempo of various developmental tasks within projects.
4) The existence of a design system will help new teams immensely and existing teams can also avail themselves of its benefits. Furthermore, the availability of a design system will help in increasing the retention of volunteers. 
5) The stakeholder mentioned about the creation of an MVP or a base template which can be customized by several teams according to their need and goals.

**Comment by kmedhi** [comment]
The tasks have been completed. @nasimbiglari @JeannyRen
