### ISSUE TITLE
Eric C--Listening to the stakeholder interview

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/design-systems#327]
### Overview
In order to fully understand the reasons behind changing parts of the roadmap and research objectives, it's vital to listen to the stakeholder interview. As you are listening to this interview please keep in mind the objectives of it:

- Identify business Goals and expectations.
- Understand the background of the project and its constraints.
- Identify the pain points.
- Discover the best approach to implement the design system
- Explore the possible effect of the design system on the team onboarding.
- Identify the types of projects in which the design system could be beneficial

### Action Items

- [x] Listen to the stakeholder interview
- [x] Makes note on things that stood out for you ( This can be a theme, pattern, interesting observation)
- [x] share your notes in the comment section below

### Resources/Instructions
[Stakeholder interview](https://drive.google.com/drive/u/0/folders/150KlP6XgUIhdNvvo9NseI0cP8mtn1KrB)

**Comment by cunninghamej** [comment]
-400 to 450 HfLA active members at the moment (Slack)—150 project volunteers at any given time.

-With the variability in project length and scope, likely also team membership—what would a good design system look like.

-If numbers of team members are variable and hard to know. . .what sorts of things can or should a design system have in order to maintain some semblance of stability and visibility with projects [lots of documentation, as well as frameworks for how to document]

-Stakeholder “B” thinks that this will eventually be a design system for use across civic tech since Hack for LA has the resources.

-Stakeholder “B” does not seem to have a clear understanding of design systems [as I understand them after doing research]

-“Perfect is the enemy of the good,” [understand the sentiment, but. . .hmmm]


Pain points
1. difficulty of building a design system that meets the needs of a volunteer based organization like Hack for LA in which project length and scope as well as volunteer length and scope are constantly shifting
2. Multiple (mis)understandings of what a design system is and what itʻs components are: design patterns, style guides, etc. 
3. How do we do this project as an ongoing project when volunteers will come and go even in this project? How do we build a foundation that is itself shifting? [Design system includes the people, processes, and culture that defines an organization. Not just tangible things.]



Think that this team (UX researchers in particular) can help with this. We need to not only be thinking about templates and such, we need to be thinking about how to define processes and culture that empowers people to take part in the design system—how to document, how to use, how to contribute.
