### ISSUE TITLE
Review Research interview questions

### ISSUE THREAD

**Issue by BobbyBishopUX** [hackforla/design-systems#66]
### Overview
Sort collected interview questions from [DS - Interview Questions](https://docs.google.com/document/d/1fLzb_hrqgfjioXxDDOOMfMgT2oJ3Gi3h1snCOAWWEcc/edit?usp=sharing)

### Action Items
This Issue is dependent on the completion of the below Issues:

- [x] #35 
- [x] #36 
- [x] #37 
- [x] #130 
- [x]  #129 
- [x] Review #32 

### Resources/Instructions
Being done here: [Document](https://docs.google.com/document/d/1g3RJRRajj8VHBe5WA1iw6SvvACUSqt-8S72f4WRBQe0/edit?usp=sharing)

**Comment by Hanastevenson** [comment]
This Issue was created before the Research plan and PM going through the backlog. This Issue is a Review Issue and is dependent on the below Issues. It will be moved back into the 'In Progress', once the below are completed this Issue is ready to be worked on.  Individual Issues have been created:

[Research interview questions & script for PM's]( https://github.com/hackforla/design-systems/issues/35 )
[Create interview questions & script for designers](https://github.com/hackforla/design-systems/issues/36) 
[Create an interview questions & script for Developers](https://github.com/hackforla/design-systems/issues/37)
[Create interview questions and script for New Joiner](https://github.com/hackforla/design-systems/issues/130)
[Create interview questions and script for stakeholder ](https://github.com/hackforla/design-systems/issues/129)

The PM will now change this Issue's title to 'Review Research interview questions'.

**Comment by nasimbiglari** [comment]
All interview questions are finalized and the scripts are all written in the designated documents.
